@startuml
class Contrat 
{
    + IdContrat : int
    + Type : int
    + TpsLun : int
    + TpsMar : int
    + TpsMer : int
    + TpsJeu : int
    + TpsVen : int
    + TotHSemaine : int
    + SalaireNet : int
    + ResteAPayer : int
}

class Enfant
{
    + IdEnfant : int
    + Nom : string
    + Prenom : string
    + IdContrat : int
}
Contrat "1,1"--|{"1,1" Enfant : IdContrat

class Mois 
{
    + IdMois : int
    + Date : date

    + TotHMois : int
    + NbJAccueil : int
    + IndemEntretien : int
    + IndemRepas : int
    + NbJActivite : int
    + SalaireNetPaye : int
    + MontantNetPaye : int

}

class Garde
{
    + IdGarde : int
    + Date : date 
    + NbHeures : int
    + IdEnfant : int
}

Enfant "1" --|{ "1..*" Garde : IdEnfant

class JoinGardeMois
{
    + IdGarde : int
    + IdMois : int
}

Garde -- JoinGardeMois
Mois -- JoinGardeMois

class Impot
{
    + IdImpot : int
    + Annee : int
    + IdEnfant : int
}

class JoinImpot
{
    + IdGarde : int
    + IdMois : int
    + IdImpot : int
}

Impot -- JoinImpot
JoinGardeMois -- JoinImpot

@enduml